title: "Sicilian Trip with Mathis"
description: ""
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal

lang: en
timezone: Europe/Rome

header_pages:
 - index.md
 - catania.md
 - catania_food.md
 - taormina.md
 - siracusa.md

