title: "Sicilian Trip with Mathis"
description: ""
show_downloads: false
google_analytics: 
remote_theme: cotes2020/jekyll-theme-chirpy

lang: en
timezone: Europe/Rome

header_pages:
 - index.md
 - catania.md
 - catania_food.md
 - taormina.md
 - siracusa.md

tabs:
 - title: Index
  url: /
 - title: Catania
  url: /catania/
 - title: Catanian Food
  url: /catania_food/
 - title: Taormina
  url: /taormina/
 - title: Siracusa
  url: /siracusa/
